services:
  - type: web
    name: sistema-fardamentos
    env: python
    plan: free
    branch: main
    script: streamlit run app.py
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
